[build]
  command = ""
  publish = "."

[context.production]
  publish = "."
  [[redirects]]
    from = "/"
    to = "/examples/index.html"
    status = 200
    force = true
  [[redirects]]
    from = "/examples/*"
    to = "/examples/:splat"
    status = 200
    force = true
  [[redirects]]
    from = "/docs"
    to = "/DOCUMENTATION/README.md"
    status = 200
    force = true
  [[redirects]]
    from = "/docs/"
    to = "/DOCUMENTATION/README.md"
    status = 200
    force = true
  [[redirects]]
    from = "/docs/*"
    to = "/DOCUMENTATION/:splat"
    status = 200
    force = true
  # Fallback redirect
  [[redirects]]
    from = "/*"
    to = "/examples/index.html"
    status = 200

[context.deploy-preview]
  publish = "."