[build]
  command = "npm run build"
  publish = "dist"

[context.production]
  publish = "dist"
  [[redirects]]
    from = "/intestacy-calculator.min.js"
    to = "/intestacy-calculator.min.js"
    status = 200
    force = true
  [[redirects]]
    from = "/intestacy-calculator.min.css"
    to = "/intestacy-calculator.min.css"
    status = 200
    force = true
  [[redirects]]
    from = "/*"
    to = "/examples/index.html"
    status = 200

[context.deploy-preview]
  publish = "dist"