[build]
  command = "npm run build"
  publish = "dist"

[context.production]
  publish = "dist"
  [[redirects]]
    from = "/"
    to = "/index.html"
    status = 200

[context.deploy-preview]
  publish = "dist"