[build]
  command = "npm run build"
  publish = "dist/examples"

[context.production]
  publish = "dist/examples"
  [[redirects]]
    from = "/*"
    to = "/index.html"
    status = 200

[context.deploy-preview]
  publish = "dist/examples"