[build]
  command = ""
  publish = "."

[context.production]
  publish = "."
  [[redirects]]
    from = "/"
    to = "/examples/index.html"
    status = 200
    force = true
  [[redirects]]
    from = "/examples/*"
    to = "/:splat"
    status = 200
    force = true
  [[redirects]]
    from = "/docs/README.md"
    to = "/docs/README.md"
    status = 200
    force = true
  [[redirects]]
    from = "/docs/DEVELOPMENT.md"
    to = "/docs/DEVELOPMENT.md"
    status = 200
    force = true
  # Restrict access to other docs files
  [[redirects]]
    from = "/docs/*"
    to = "/examples/index.html"
    status = 404
    force = true
  # Fallback redirect
  [[redirects]]
    from = "/*"
    to = "/examples/index.html"
    status = 404

[context.deploy-preview]
  publish = "."